.\" Manpage for jet.
.\" For bug reports, contact nicolo.santamaria@proton.me.
.TH jet 1 "2023-10-18" "jet man page"

.SH NAME
jet \- Just Edit Text

.SH SYNOPSIS
.B jet [OPTIONS] pattern replacement input-files...
.br
.B jet [OPTIONS] -e pattern1 replacement1 -e pattern2 replacement2 input-files...

.SH DESCRIPTION
Jet is a fast and intuitive command-line tool for find and replace operations.
.P
It replaces all occurrences of the specified regular expression patterns with the provided replacement text.
.P
Jet can process single files or entire directories specified on the command line.
.P
When given a directory, Jet descends into the directory tree and recursively finds and replaces matches in all files.

.SH OPTIONS
.TP
.B \-p
Print to stdout instead of modifying files.

.TP
.B \-v
Enable verbose mode; explain what is being done.

.TP
.B \-g \fIglob-pattern\fR
Only process files matching the given glob pattern.

.TP
.B \-a
Include hidden files (those starting with a dot).

.TP
.B \-l \fIint\fR
Maximum depth for directory traversal.

.TP
.B \-r\fR, \fB\-\-replace\-names
Replace matches in file and directory names.

.TP
.B \-n\fR, \fB\-\-names\-only
Only replace matching names, ignoring file contents.

.TP
.B \-e \fIpattern replacement\fR
Specify a regular expression pattern and replacement.
Can be used multiple times for multiple replacements.

.TP
.B \-h\fR, \fB\-\-help
Prints this help message and exits.

.SH NOTICE
When using the \-e flag multiple times, the pattern-replacement pairs are executed in the same order they are specified, one by one.

.SH EXAMPLES
.TP
.B jet "foo" "bar" my/path1 my/path2
Replace all occurrences of "foo" with "bar" in the files under \fImy/path1\fR and \fImy/path2\fR.

.TP
.B jet \-e "foo" "bar" \-e "baz" "qux" my/path1 my/path2
Replace all occurrences of "foo" with "bar" and "baz" with "qux" in the files under \fImy/path1\fR and \fImy/path2\fR.

.TP
.B jet \-p \-v "foo" "bar" my/path1
Replace "foo" with "bar" in \fImy/path1\fR and print the results to stdout with verbose output.

.TP
.B jet \-n "foo" "bar" my/path1
Rename files and directories by replacing "foo" with "bar" in their names under \fImy/path1\fR, without modifying file contents.

.TP
.B jet \-e "foo" "bar" \-e "baz" "qux" \-g "*.txt" \-a my/path1
Replace "foo" with "bar" and "baz" with "qux" in all text files, including hidden files, under \fImy/path1\fR.

.SH COPYRIGHT
Jet Copyright (C) 2023  Nicolò Santamaria
This program comes with ABSOLUTELY NO WARRANTY; for details refer to https://www.gnu.org/licenses/gpl-3.0.html.
This is free software, and you are welcome to change and redistribute it under the conditions defined by the license.

.SH AUTHOR
Written by Nicolò Santamaria <nicolo.santamaria@proton.me>.
